/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import Datos.Contenido;
import Gestion.GestionContenidos;
import Tablas.ListarContenidos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Contenidos extends javax.swing.JInternalFrame {

    GestionContenidos cont=new GestionContenidos();
    
    public Contenidos() {
        initComponents();
    }

    private void limpiar(){
        txtId.setText("");
        txtNombre.setText("");
        txtObsevaciones.setText("");
        txtDescripccion.setText("");
        txtId.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimipiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObsevaciones = new javax.swing.JTextArea();
        btnListar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripccion = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(628, 474));
        setMinimumSize(new java.awt.Dimension(628, 474));
        setPreferredSize(new java.awt.Dimension(628, 474));

        bg.setBackground(new java.awt.Color(57, 57, 57));
        bg.setMaximumSize(new java.awt.Dimension(580, 430));
        bg.setName(""); // NOI18N
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, 360));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 154, 118));
        jLabel1.setText("Contenidos");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 154, 118));
        jLabel5.setText("Nombre:");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(18, 154, 118));
        jLabel6.setText("Decripcción:");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(18, 154, 118));
        jLabel7.setText("Observaciones:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 120, 20));
        bg.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 160, 30));
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 160, 30));

        btnBuscar.setBackground(new java.awt.Color(18, 154, 118));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        bg.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 110, 30));

        btnEliminar.setBackground(new java.awt.Color(18, 154, 118));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 250, 30));

        btnEditar.setBackground(new java.awt.Color(18, 154, 118));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        bg.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 110, 30));

        btnLimipiar.setBackground(new java.awt.Color(18, 154, 118));
        btnLimipiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimipiar.setText("Limpiar");
        btnLimipiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimipiarActionPerformed(evt);
            }
        });
        bg.add(btnLimipiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 250, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(18, 154, 118));
        jLabel8.setText("Id:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, 20));

        btnGuardar.setBackground(new java.awt.Color(18, 154, 118));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        bg.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 250, 30));

        txtObsevaciones.setColumns(20);
        txtObsevaciones.setRows(5);
        jScrollPane1.setViewportView(txtObsevaciones);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 280, 90));

        btnListar1.setBackground(new java.awt.Color(18, 154, 118));
        btnListar1.setForeground(new java.awt.Color(255, 255, 255));
        btnListar1.setText("Listar");
        btnListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar1ActionPerformed(evt);
            }
        });
        bg.add(btnListar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 250, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/content.png"))); // NOI18N
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        txtDescripccion.setColumns(20);
        txtDescripccion.setRows(5);
        jScrollPane2.setViewportView(txtDescripccion);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 280, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            Contenido contenido= cont.BuscarContenido(txtId.getText());
            if (contenido != null) {
                //se ubican los resultados obtenidos de la funcion ConsultarUsuarios
                txtId.setText(contenido.getCodigo());
                txtNombre.setText(contenido.getNombre());
                txtDescripccion.setText(contenido.getDescripccion());    
                txtObsevaciones.setText(contenido.getObservaciones());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Contenidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       if (cont.eliminarContenido(txtId.getText()) == true) {
            JOptionPane.showMessageDialog(null, "Contenido elminado exitosamente");
            //llamo a la funcion limpiar para limpiar las entradas 
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Nose pudo eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
         cont.actualizarContenido(new Contenido(txtId.getText(),
                                             txtNombre.getText(),
                                             txtDescripccion.getText(),
                                             txtObsevaciones.getText()));
          limpiar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         cont.InsertarContenido(new Contenido(txtId.getText(),
                                             txtNombre.getText(),
                                             txtDescripccion.getText(),
                                             txtObsevaciones.getText()));
          limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar1ActionPerformed
        ListarContenidos lc= new ListarContenidos();
        ///añadimos el Formulario al DesktopPane
        this.getParent().add(lc);
        //hacemos visible Formulario
        lc.setVisible(true);
    }//GEN-LAST:event_btnListar1ActionPerformed

    private void btnLimipiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimipiarActionPerformed
       limpiar();
    }//GEN-LAST:event_btnLimipiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimipiar;
    private javax.swing.JButton btnListar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea txtDescripccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObsevaciones;
    // End of variables declaration//GEN-END:variables
}
