package vistas;

import Datos.Emprendedores;
import Gestion.GestionEmprendedor;
import Tablas.ListarEmprendedor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Emprendedor extends javax.swing.JInternalFrame {
    
    GestionEmprendedor ge = new GestionEmprendedor();
    private String sexo;
    
    public Emprendedor() {
        initComponents();
    }
    
    private void limpiar() {
        txtDescripTienda.setText("");
        txtDireccion.setText("");
        txtDireccionTienda.setText("");
        txtEmail.setText("");
        txtFbTienda.setText("");
        txtId.setText("");
        txtMapsTienda.setText("");
        txtNombre.setText("");
        txtNombreTienda.setText("");
        txtObservaciones.setText("");
        txtTelefono.setText("");
        bgSexo.clearSelection();  //Button Group
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtDireccionTienda = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        rbtFemenino = new javax.swing.JRadioButton();
        rbtMasculio = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        txtMapsTienda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar4 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtNombreTienda = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDescripTienda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtFbTienda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Emprendedor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        bg.setBackground(new java.awt.Color(57, 57, 57));
        bg.setMaximumSize(new java.awt.Dimension(800, 600));
        bg.setMinimumSize(new java.awt.Dimension(800, 600));
        bg.setName("Emprendedor"); // NOI18N
        bg.setPreferredSize(new java.awt.Dimension(800, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 10, 560));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(18, 154, 118));
        jLabel4.setText("Tienda");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 60, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(18, 154, 118));
        jLabel14.setText("Nombre:");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(18, 154, 118));
        jLabel15.setText("Facebook:");
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 100, 20));
        bg.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, 30));
        bg.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 230, 30));

        btnBuscar.setBackground(new java.awt.Color(18, 154, 118));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        bg.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 290, 30));

        btnEditar.setBackground(new java.awt.Color(18, 154, 118));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        bg.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 290, 30));

        btnListar.setBackground(new java.awt.Color(18, 154, 118));
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        bg.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 320, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(18, 154, 118));
        jLabel17.setText("Id:");
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, 20));

        btnLimpiar.setBackground(new java.awt.Color(18, 154, 118));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        bg.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 320, 30));
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 230, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(18, 154, 118));
        jLabel18.setText("Telefono:");
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 20));
        bg.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(18, 154, 118));
        jLabel19.setText("Sexo:");
        bg.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(18, 154, 118));
        jLabel20.setText("Email:");
        bg.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 20));
        bg.add(txtDireccionTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 320, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(18, 154, 118));
        jLabel21.setText("Dirección:");
        bg.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 20));
        bg.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 230, 30));

        bgSexo.add(rbtFemenino);
        rbtFemenino.setForeground(new java.awt.Color(0, 0, 0));
        rbtFemenino.setText("Femenino");
        rbtFemenino.setBorder(null);
        rbtFemenino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtFemeninoMouseClicked(evt);
            }
        });
        bg.add(rbtFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 110, 30));

        bgSexo.add(rbtMasculio);
        rbtMasculio.setForeground(new java.awt.Color(0, 0, 0));
        rbtMasculio.setText("Masculino");
        rbtMasculio.setBorder(null);
        rbtMasculio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtMasculioMouseClicked(evt);
            }
        });
        bg.add(rbtMasculio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 100, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(18, 154, 118));
        jLabel22.setText("Emprendedor");
        bg.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, 30));
        bg.add(txtMapsTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 320, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(18, 154, 118));
        jLabel8.setText("Nombre:");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(18, 154, 118));
        jLabel7.setText("Observaciones:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 120, 20));

        btnGuardar4.setBackground(new java.awt.Color(18, 154, 118));
        btnGuardar4.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar4.setText("Guardar");
        btnGuardar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar4ActionPerformed(evt);
            }
        });
        bg.add(btnGuardar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 290, 30));

        btnEliminar.setBackground(new java.awt.Color(18, 154, 118));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 290, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(18, 154, 118));
        jLabel16.setText("Descripción:");
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 100, 20));
        bg.add(txtNombreTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 320, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(18, 154, 118));
        jLabel23.setText("GoogleMaps:");
        bg.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 100, 20));
        bg.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 230, 30));
        bg.add(txtDescripTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 320, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(18, 154, 118));
        jLabel12.setText("Dirección:");
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 100, 20));
        bg.add(txtFbTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 320, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entrepreneur-64.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            Emprendedores emprendedor = ge.BuscarEmprendedor(txtId.getText());
            if (emprendedor != null) {
                //se ubican los resultados obtenidos de la funcion ConsultarUsuarios
                txtId.setText(emprendedor.getId());
                txtNombre.setText(emprendedor.getNombre());
                txtTelefono.setText(emprendedor.getTelefono());
                    
                if (emprendedor.getSexo().equals("Masculino")){
                        rbtMasculio.setSelected(false);
                    } else {
                        rbtFemenino.setSelected(false);
                    }
                txtEmail.setText(emprendedor.getEmail());
                txtDireccion.setText(emprendedor.getDireccion());
                txtNombreTienda.setText(emprendedor.getNombreTienda());
                txtDescripTienda.setText(emprendedor.getDescripcionTienda());
                txtMapsTienda.setText(emprendedor.getGoogleMaps());
                txtFbTienda.setText(emprendedor.getFacebookTienda());
                txtDireccionTienda.setText(emprendedor.getDireccionTienda());
                txtObservaciones.setText(emprendedor.getObservaciones());   
            }
        } catch (SQLException ex) {
            Logger.getLogger(Contenidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        ge.actualizarEmprendedor(new Emprendedores(
                txtId.getText(), txtNombre.getText(), txtTelefono.getText(), 
                sexo, txtEmail.getText(), txtDireccion.getText(), txtNombreTienda.getText(),
                txtDescripTienda.getText(), txtMapsTienda.getText(), txtFbTienda.getText(),
                txtDireccionTienda.getText(), txtObservaciones.getText()
        ));
        limpiar();        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar4ActionPerformed
        ge.InsertarEmprendedor(new Emprendedores(
                txtId.getText(), txtNombre.getText(), txtTelefono.getText(), sexo,
                txtEmail.getText(), txtDireccion.getText(), txtNombreTienda.getText(),
                txtDescripTienda.getText(), txtMapsTienda.getText(), txtFbTienda.getText(),
                txtDireccionTienda.getText(), txtObservaciones.getText()
        ));
        limpiar();        
    }//GEN-LAST:event_btnGuardar4ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (ge.eliminarEmprendedor(txtId.getText()) == true) {
            JOptionPane.showMessageDialog(null, "Emprendedor eliminado exitosamente");
            //llamo a la funcion limpiar para limpiar las entradas 
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar");
        }
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ListarEmprendedor le = new ListarEmprendedor();
        ///añadimos el Formulario al DesktopPane
        this.getParent().add(le);
        //hacemos visible Formulario 
        le.setVisible(true);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void rbtMasculioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtMasculioMouseClicked
        sexo = "Masculino";
    }//GEN-LAST:event_rbtMasculioMouseClicked

    private void rbtFemeninoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtFemeninoMouseClicked
        sexo = "Femenino";
    }//GEN-LAST:event_rbtFemeninoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar4;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rbtFemenino;
    private javax.swing.JRadioButton rbtMasculio;
    private javax.swing.JTextField txtDescripTienda;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionTienda;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFbTienda;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMapsTienda;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreTienda;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
