package vistas;

import Gestion.GestionMentorias;
import Datos.Mentoria;
import Gestion.GestionProductos;
import Tablas.ListarMentorias;
import javax.swing.JOptionPane;
import Utilidades.Utilidades;
import java.sql.SQLException;
import java.sql.Time;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Mentorias extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mentorias
     */
    GestionMentorias gm = new GestionMentorias();
    GestionProductos gp = new GestionProductos();

    Utilidades ut = new Utilidades();

    public Mentorias() throws SQLException {
        initComponents();
        Components();
    }

    private void Components() throws SQLException {
        txtFecha.setMinSelectableDate(new Date());
        llenarComboBoxEncargado();
        llenarComboEmprendedores();
        llenarComboBoxContenido();
    }

    private void llenarComboBoxEncargado() throws SQLException {
        gm.llenarComboBox("id_enc", "encargado_mentoria", cboIdEncargado);
    }

    private void llenarComboEmprendedores() throws SQLException {
        gp.llenarComboBox("id_emp", cboIdEmprendedor);
    }

    private void llenarComboBoxContenido() throws SQLException {
        gm.llenarComboBox("codigo_con", "contenido", cboIdContenido);
    }

    private void limpiar() {
        txtIdMentoria.setText("");
        cboIdContenido.setSelectedIndex(0);
        cboIdEmprendedor.setSelectedIndex(0);
        cboIdEncargado.setSelectedIndex(0);
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtFecha.setCalendar(null);
        txtHora.setText("");
        txtObservaciones.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdEncargado = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtIdMentoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        txtObservaciones = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        cboIdContenido = new javax.swing.JComboBox<>();
        cboIdEncargado = new javax.swing.JComboBox<>();
        cboIdEmprendedor = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        timePicker1 = new com.raven.swing.TimePicker();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(710, 650));
        setMinimumSize(new java.awt.Dimension(710, 650));
        setName("Mentorías"); // NOI18N
        setPreferredSize(new java.awt.Dimension(710, 650));

        txtIdEncargado.setBackground(new java.awt.Color(57, 57, 57));
        txtIdEncargado.setMaximumSize(new java.awt.Dimension(700, 630));
        txtIdEncargado.setMinimumSize(new java.awt.Dimension(700, 630));
        txtIdEncargado.setName("Mentorias"); // NOI18N
        txtIdEncargado.setPreferredSize(new java.awt.Dimension(700, 630));
        txtIdEncargado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        txtIdEncargado.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 10, 410));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 154, 118));
        jLabel1.setText("Mentorías");
        txtIdEncargado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 154, 118));
        jLabel5.setText("Nombre:");
        txtIdEncargado.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(18, 154, 118));
        jLabel6.setText("Hora:");
        txtIdEncargado.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 60, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(18, 154, 118));
        jLabel7.setText("Observaciones:");
        txtIdEncargado.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 120, 20));
        txtIdEncargado.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 180, 30));

        btnLimpiar.setBackground(new java.awt.Color(18, 154, 118));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        txtIdEncargado.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 240, 30));

        btnEliminar.setBackground(new java.awt.Color(18, 154, 118));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        txtIdEncargado.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 130, 60));

        btnEditar.setBackground(new java.awt.Color(18, 154, 118));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        txtIdEncargado.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 110, 30));

        btnListar.setBackground(new java.awt.Color(18, 154, 118));
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        txtIdEncargado.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 240, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(18, 154, 118));
        jLabel8.setText("Id Contenido:");
        txtIdEncargado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));

        btnGuardar.setBackground(new java.awt.Color(18, 154, 118));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        txtIdEncargado.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 230, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(18, 154, 118));
        jLabel9.setText("Id Mentoria:");
        txtIdEncargado.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 20));
        txtIdEncargado.add(txtIdMentoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 200, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(18, 154, 118));
        jLabel10.setText("Id Encargado:");
        txtIdEncargado.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(18, 154, 118));
        jLabel11.setText("Id Emprendedor:");
        txtIdEncargado.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));
        txtIdEncargado.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 180, 30));

        txtHora.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        txtIdEncargado.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 230, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(18, 154, 118));
        jLabel13.setText("Descripción:");
        txtIdEncargado.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(18, 154, 118));
        jLabel12.setText("Fecha:");
        txtIdEncargado.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 100, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mentorship_1.png"))); // NOI18N
        txtIdEncargado.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, 70));

        btnBuscar1.setBackground(new java.awt.Color(18, 154, 118));
        btnBuscar1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        txtIdEncargado.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 110, 30));
        txtIdEncargado.add(txtObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 180, 30));

        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setDateFormatString("yyyy-MM-dd");
        txtFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtIdEncargado.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 230, 40));

        cboIdContenido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cboIdContenido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contenido" }));
        txtIdEncargado.add(cboIdContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 200, -1));

        cboIdEncargado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cboIdEncargado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Encargado" }));
        txtIdEncargado.add(cboIdEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, -1));

        cboIdEmprendedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cboIdEmprendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emprendedor" }));
        txtIdEncargado.add(cboIdEmprendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, -1));
        txtIdEncargado.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 350, 10));

        timePicker1.setForeground(new java.awt.Color(18, 154, 118));
        timePicker1.setDisplayText(txtHora);
        timePicker1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        timePicker1.setName(""); // NOI18N
        txtIdEncargado.add(timePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIdEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (gm.eliminarMentoria(txtIdMentoria.getText()) == true) {
            JOptionPane.showMessageDialog(null, "Mentoria eliminada exitosamente");
            //llamo a la funcion limpiar para limpiar las entradas 
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar");
        }
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String fecha = ((JTextField) txtFecha.getDateEditor().getUiComponent()).getText();        

        gm.actualizarMentoria(new Mentoria(
                txtIdMentoria.getText(), txtNombre.getText(),
                txtDescripcion.getText(), fecha, txtHora.getText(),
                txtObservaciones.getText(),
                cboIdEmprendedor.getSelectedItem().toString(),
                cboIdEncargado.getSelectedItem().toString(),
                cboIdContenido.getSelectedItem().toString()
        ));
        limpiar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String fecha = ((JTextField) txtFecha.getDateEditor().getUiComponent()).getText();        
        gm.InsertarMentoria(new Mentoria(
                txtIdMentoria.getText(), txtNombre.getText(),
                txtDescripcion.getText(), fecha, txtHora.getText(),
                txtObservaciones.getText(),
                cboIdEmprendedor.getSelectedItem().toString(),
                cboIdEncargado.getSelectedItem().toString(),
                cboIdContenido.getSelectedItem().toString()
        ));
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        try {
            Mentoria ment = gm.BuscarMentoria(txtIdMentoria.getText());
            if (ment != null) {
                //se ubican los resultados obtenidos de la funcion ConsultarUsuarios
                txtIdMentoria.setText(ment.getId());
                txtNombre.setText(ment.getNombre());
                txtDescripcion.setText(ment.getDescripcion());
                txtFecha.setDateFormatString(ment.getFecha());
                txtHora.setText(ment.getHora());
                txtObservaciones.setText(ment.getObservaciones());
                cboIdEmprendedor.setSelectedItem(ment.getIdEmprendedor());
                cboIdEncargado.setSelectedItem(ment.getIdEncargado());
                cboIdContenido.setSelectedItem(ment.getIdContenido());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Contenidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ListarMentorias lm = new ListarMentorias();
        this.getParent().add(lm);
        lm.setVisible(true);
    }//GEN-LAST:event_btnListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> cboIdContenido;
    private javax.swing.JComboBox<String> cboIdEmprendedor;
    private javax.swing.JComboBox<String> cboIdEncargado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.raven.swing.TimePicker timePicker1;
    private javax.swing.JTextField txtDescripcion;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JPanel txtIdEncargado;
    private javax.swing.JTextField txtIdMentoria;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
